name: Telegram Streamer

on:
  workflow_dispatch: # تشغيل يدوي

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350 # لضمان استمرار البث لأطول فترة ممكنة

    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming
        run: |
          while true; do
            ffmpeg -hide_banner -loglevel error \
            -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 5 \
            -i 'http://g.cjwa05.xyz/at/sh/986979?token=ShN0YQ0JGlhBVEk9ShAWG04kBi5fWQJEC0E8WgsHJDJHQQQJQQQQQ1JHG0EQQQQQQQ0QQQ0UWwVQAVVQUwxNQ0QQQQQQQQxAWUcQAQQQQQQQRhVGQQQQQUcNUFJQDFFQBQQACEgSQQQQRw1BQQQHQQQQQEYcFAQQQQQQQQQQQQQQQQQQQRICDBYJW09EV1xnBQFUBV5SQw5HBkNJRAQQQRMLXEQIXB.RAAQxDEQdMVxpbRghcBwBDGEdUDhAITRMYEwsQdSESFEAGHUMGCEtbVw9GA0ZERUMYR14SOhRcEhVDVFNcAUIaWEFVFU9EVVNAPgdWCl5TAkAMQQQQRANDQBMdEFQQQQQQAQQQEQQQEAJDQQQQQQQQQ0dK' \
            -c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p \
            -b:v 2500k -maxrate 2500k -bufsize 5000k \
            -vf "fps=25,scale=1280:-2,format=yuv420p" -g 50 \
            -c:a aac -b:a 96k -ar 44100 \
            -f flv "rtmps://dc4-1.rtmp.t.me/s/2625753690:ayM9m5yb2zNYxOLNUd83Sw"
            
            echo "إعادة الاتصال..."
            sleep 2
          done
