name: 📡 Live Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update -qq && sudo apt-get install -y ffmpeg -qq

      - name: Stream
        run: |
          while true; do
            ffmpeg -hide_banner -loglevel warning \
            -user_agent "Mozilla/5.0" \
            -headers "Referer: https://mrayham-netfly.hf.space/" \
            -fflags +genpts+discardcorrupt \
            -f dash \
            -i 'https://mrayham-netfly.hf.space/stream/1-720p.mpd' \
            -map 0:v:0 -map 0:a:0 \
            -c:v libx264 \
            -preset superfast \
            -tune zerolatency \
            -x264opts keyint=50:min-keyint=50:no-scenecut \
            -pix_fmt yuv420p \
            -b:v 2500k -maxrate 2500k -bufsize 5000k \
            -c:a aac -b:a 128k -ac 2 -ar 44100 \
            -f flv \
            "rtmps://dc4-1.rtmp.t.me/s/2469921338:bsK9F5BRae81ZMRCvUZFgA"
            sleep 3
          done
