name: Final Monter

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming
        run: |
          while true; do
            ffmpeg -hide_banner -loglevel error \
            -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 5 \
            -i 'http://str2.v3v3v.xyz/live/Nabil_384986/MATxRQG3/1356800.m3u8' \
            -c:v libx264 -preset veryfast -tune zerolatency -pix_fmt yuv420p \
            -b:v 2500k -maxrate 2500k -bufsize 5000k \
            -vf "fps=30,scale=1280:720,format=yuv420p,drawtext=text='t.me/xl9rr':fontsize=28:fontcolor=white@0.7:x=w-mod(t*90\,(w+tw)):y=h-62" \
            -g 60 -sc_threshold 0 \
            -c:a aac -b:a 100k -ar 44100 \
            -f flv "rtmps://dc4-1.rtmp.t.me/s/2625753690:7vTtB4e37OUyPiAGGgdm5A"
            
            echo "إعادة الاتصال..."
            sleep 2
          done
